platform :ios, '7.0'
source "https://github.com/Cocoapods/Specs"
inhibit_all_warnings!

target :MEDCategoriesDemo, :exclusive => true do
  pod 'MEDCategories', :path => '../MEDCategories.podspec'
end
